CREATE TABLE IF NOT EXISTS planet (
  planet_id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL UNIQUE,
  description TEXT,
  distance_from_earth NUMERIC,
  star_id INT,
  has_life BOOLEAN NOT NULL,

  PRIMARY KEY(planet_id),
  FOREIGN KEY(star_id) REFERENCES star
  );