CREATE TABLE IF NOT EXISTS star (
  star_id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR NOT NULL UNIQUE,
  description TEXT,
  age_in_millions_of_years INT NOT NULL,
  galaxy_id INT,

  PRIMARY KEY(star_id),
  FOREIGN KEY(galaxy_id) REFERENCES galaxy
  );